version: "2"
# Seems docker-compose prefixes the services with the root project name which is "jarvis"
services:
    data-api:
        depends_on:
            - redis
            - elasticsearch
        # TODO: environment approach vs env_file approach
        environment:
            - JARVIS_DATA_VERSION=${JARVIS_DATA_VERSION}
        image: registry.gitlab.com/mikehwang/jarvis-api:0.12.0
        links:
            - redis:redis.jarvis.home
            - elasticsearch:elasticsearch.jarvis.home
        ports:
            - "3000:3000"
        volumes:
            - "${JARVIS_DIR_ROOT}:/opt/jarvis"
    elasticsearch:
        image: elasticsearch:2.3.3
        ports:
            - "9200:9200"
        volumes:
            - "${JARVIS_DIR_ROOT}/Elasticsearch/:/usr/share/elasticsearch/data"
    redis:
        command: redis-server --appendonly yes
        image: redis:3.2.1
        ports:
            - "6379:6379"
        volumes:
            - "${JARVIS_DIR_ROOT}/Redis/:/data"
