version: "2"
# Seems docker-compose prefixes the services with the root project name which is "jarvis"
services:
    nginx:
        depends_on:
            - data-api
        image: nginx:1.11.6
        links:
            - data-api:data-api.jarvis.home
        ports:
            - 80:80
        volumes:
            - ${JARVIS_DIR_ROOT}/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ${JARVIS_DIR_ROOT}/etc/nginx/htpasswd:/etc/nginx/htpasswd
        restart: unless-stopped
    data-api:
        depends_on:
            - redis
            - elasticsearch
        # TODO: environment approach vs env_file approach
        environment:
            - JARVIS_DATA_VERSION=${JARVIS_DATA_VERSION}
        image: clb6/jarvis-api:1.0.0
        links:
            - redis:redis.jarvis.home
            - elasticsearch:elasticsearch.jarvis.home
        volumes:
            - "${JARVIS_DIR_ROOT}:/opt/jarvis"
        restart: unless-stopped
    elasticsearch:
        image: elasticsearch:2.3.3
        volumes:
            - "${JARVIS_DIR_ROOT}/Elasticsearch/:/usr/share/elasticsearch/data"
        restart: unless-stopped
    redis:
        command: redis-server --appendonly yes
        image: redis:3.2.1
        volumes:
            - "${JARVIS_DIR_ROOT}/Redis/:/data"
        restart: unless-stopped
